### ISSUE TITLE
Unclear, missing instructions & JWKS issues

### ISSUE THREAD

**Issue by Jhappy77** [FusionAuth/fusionauth-example-modern-guide-to-oauth#1]
The following steps are listed in instructions:

* create rsa key
* enable jwt in app
* change signing algos to be rsa key

However, they are not elaborated on anywhere, are seemingly not discussed in the [accompanying guide](https://fusionauth.io/articles/oauth/modern-guide-to-oauth#authorization-code-grant) (or if they are, it's not clear). 

Rather than assuming we know how to do this, please give instructions. 

Probably related to this issue:
When I use this repo, sign in appears to work initially, except shortly after the redirect to todos I get the following error:
```
\fusionauth-example-modern-guide-to-oauth\node_modules\jwks-rsa\lib\JwksClient.js:139
          return cb(new _JwksError2.default('The JWKS endpoint did not contain any keys'));
                    ^
JwksError: The JWKS endpoint did not contain any keys
```

Please clarify what's expected. Thanks!

**Comment by mooreds** [comment]
Thanks @Jhappy77 . You can get an RSA key by:

* logging into the fusionauth admin
* navigating to 'settings -> key master' 
* creating a new RSA key
* navigating to 'tenants -> Your tenant -> JWT' 
* configuring the access token and id token to be signed by the new RSA key you created

That should solve your issue.

I'll leave this issue open to update the README. We should also create a kickstart for easier experimentation.

Thanks for considering FusionAuth!

**Comment by mooreds** [comment]
Heya, I updated and revised this application so that now you can stand up FusionAuth and have the RSA key automatically generated with Kickstart. Please see the new README.

I'm going to close this issue out, but please re-open if you run into any issues.

Thanks!
